<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/11/25 14:10:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=resgala',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
