<?php

/**
 * BaseReservation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nom
 * @property string $prenom
 * @property string $login
 * @property string $repas_with
 * @property enum $paye_with
 * @property string $banque_nom
 * @property timestamp $validated_at
 * @property timestamp $payed_at
 * @property Doctrine_Collection $Produits
 * @property LigneCommande $LigneCommandes
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getNom()            Returns the current record's "nom" value
 * @method string              getPrenom()         Returns the current record's "prenom" value
 * @method string              getLogin()          Returns the current record's "login" value
 * @method string              getRepasWith()      Returns the current record's "repas_with" value
 * @method enum                getPayeWith()       Returns the current record's "paye_with" value
 * @method string              getBanqueNom()      Returns the current record's "banque_nom" value
 * @method timestamp           getValidatedAt()    Returns the current record's "validated_at" value
 * @method timestamp           getPayedAt()        Returns the current record's "payed_at" value
 * @method Doctrine_Collection getProduits()       Returns the current record's "Produits" collection
 * @method LigneCommande       getLigneCommandes() Returns the current record's "LigneCommandes" value
 * @method Reservation         setId()             Sets the current record's "id" value
 * @method Reservation         setNom()            Sets the current record's "nom" value
 * @method Reservation         setPrenom()         Sets the current record's "prenom" value
 * @method Reservation         setLogin()          Sets the current record's "login" value
 * @method Reservation         setRepasWith()      Sets the current record's "repas_with" value
 * @method Reservation         setPayeWith()       Sets the current record's "paye_with" value
 * @method Reservation         setBanqueNom()      Sets the current record's "banque_nom" value
 * @method Reservation         setValidatedAt()    Sets the current record's "validated_at" value
 * @method Reservation         setPayedAt()        Sets the current record's "payed_at" value
 * @method Reservation         setProduits()       Sets the current record's "Produits" collection
 * @method Reservation         setLigneCommandes() Sets the current record's "LigneCommandes" value
 * 
 * @package    resgala
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReservation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reservation');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nom', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('prenom', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('login', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('repas_with', 'string', 256, array(
             'type' => 'string',
             'length' => 256,
             ));
        $this->hasColumn('paye_with', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'especes',
              1 => 'cheque',
             ),
             ));
        $this->hasColumn('banque_nom', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('validated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('payed_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));


        $this->index('LoginINSA', array(
             'fields' => 
             array(
              0 => 'login',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Produit as Produits', array(
             'refClass' => 'LigneCommande',
             'local' => 'reservation_id',
             'foreign' => 'produit_id'));

        $this->hasOne('LigneCommande as LigneCommandes', array(
             'local' => 'id',
             'foreign' => 'reservation_id'));
    }
}