<?php

/**
 * BaseLigneCommande
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $reservation_id
 * @property integer $produit_id
 * @property integer $quantite
 * @property Reservation $Reservation
 * @property Produit $Produit
 * 
 * @method integer       getReservationId()  Returns the current record's "reservation_id" value
 * @method integer       getProduitId()      Returns the current record's "produit_id" value
 * @method integer       getQuantite()       Returns the current record's "quantite" value
 * @method Reservation   getReservation()    Returns the current record's "Reservation" value
 * @method Produit       getProduit()        Returns the current record's "Produit" value
 * @method LigneCommande setReservationId()  Sets the current record's "reservation_id" value
 * @method LigneCommande setProduitId()      Sets the current record's "produit_id" value
 * @method LigneCommande setQuantite()       Sets the current record's "quantite" value
 * @method LigneCommande setReservation()    Sets the current record's "Reservation" value
 * @method LigneCommande setProduit()        Sets the current record's "Produit" value
 * 
 * @package    resgala
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLigneCommande extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ligne_commande');
        $this->hasColumn('reservation_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('produit_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('quantite', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Reservation', array(
             'local' => 'reservation_id',
             'foreign' => 'id'));

        $this->hasOne('Produit', array(
             'local' => 'produit_id',
             'foreign' => 'id'));
    }
}