<?php

/**
 * BaseProduit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $intitule
 * @property string $description
 * @property decimal $prix
 * @property Doctrine_Collection $Reservation
 * @property Doctrine_Collection $LigneCommande
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getIntitule()      Returns the current record's "intitule" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method decimal             getPrix()          Returns the current record's "prix" value
 * @method Doctrine_Collection getReservation()   Returns the current record's "Reservation" collection
 * @method Doctrine_Collection getLigneCommande() Returns the current record's "LigneCommande" collection
 * @method Produit             setId()            Sets the current record's "id" value
 * @method Produit             setIntitule()      Sets the current record's "intitule" value
 * @method Produit             setDescription()   Sets the current record's "description" value
 * @method Produit             setPrix()          Sets the current record's "prix" value
 * @method Produit             setReservation()   Sets the current record's "Reservation" collection
 * @method Produit             setLigneCommande() Sets the current record's "LigneCommande" collection
 * 
 * @package    resgala
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProduit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('produit');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('intitule', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('description', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('prix', 'decimal', 5, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Reservation', array(
             'refClass' => 'LigneCommande',
             'local' => 'produit_id',
             'foreign' => 'reservation_id'));

        $this->hasMany('LigneCommande', array(
             'local' => 'id',
             'foreign' => 'produit_id'));
    }
}