<?php

/**
 * Reservation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    resgala
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Reservation extends BaseReservation
{
  public function getExpiredAt(){
    return $this->getValidatedAt() + 15*24*3600;
  }

  public function paye($force = false){
    if(!$force and $this->getExpiredAt() < date())
      return false;
    
    $this->setPayedAt(date());
    $this->save();
  }

  public function isPayed(){
    if($this->getPayedAt())
      return true;
    return false;
  }
}
