<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2010/11/25 15:04:09
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfwebdebugpaneldoctrine' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfdoctrinecli' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrinepager' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfvalidatordoctrineunique' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfvalidatordoctrinechoice' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinedatadumptask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrineinsertsqltask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinedropdbtask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinedqltask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinedataloadtask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinecreatemodeltables' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinebuildtask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinebuildschematask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinemigratetask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinebuilddbtask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegenerateadmintask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinebuildformstask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildsqltask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildmodeltask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebasetask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuildfilterstask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'swift_doctrinespool' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinedatabase' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionlistener' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrineexception' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfformdoctrine' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sftesterdoctrine' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfdoctrinerecordi18nfilter' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinerecord' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrineroute' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrinegenerator' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineformfiltergenerator' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinecolumn' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfwidgetformdoctrinechoice' => '/srv/http/resgala/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'basereservationform' => '/srv/http/resgala/lib/form/doctrine/base/BaseReservationForm.class.php',
  'baseproduitform' => '/srv/http/resgala/lib/form/doctrine/base/BaseProduitForm.class.php',
  'baselignecommandeform' => '/srv/http/resgala/lib/form/doctrine/base/BaseLigneCommandeForm.class.php',
  'produitform' => '/srv/http/resgala/lib/form/doctrine/ProduitForm.class.php',
  'reservationform' => '/srv/http/resgala/lib/form/doctrine/ReservationForm.class.php',
  'baseformdoctrine' => '/srv/http/resgala/lib/form/doctrine/BaseFormDoctrine.class.php',
  'lignecommandeform' => '/srv/http/resgala/lib/form/doctrine/LigneCommandeForm.class.php',
  'baseform' => '/srv/http/resgala/lib/form/BaseForm.class.php',
  'basereservationformfilter' => '/srv/http/resgala/lib/filter/doctrine/base/BaseReservationFormFilter.class.php',
  'baseproduitformfilter' => '/srv/http/resgala/lib/filter/doctrine/base/BaseProduitFormFilter.class.php',
  'baselignecommandeformfilter' => '/srv/http/resgala/lib/filter/doctrine/base/BaseLigneCommandeFormFilter.class.php',
  'reservationformfilter' => '/srv/http/resgala/lib/filter/doctrine/ReservationFormFilter.class.php',
  'lignecommandeformfilter' => '/srv/http/resgala/lib/filter/doctrine/LigneCommandeFormFilter.class.php',
  'baseformfilterdoctrine' => '/srv/http/resgala/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'produitformfilter' => '/srv/http/resgala/lib/filter/doctrine/ProduitFormFilter.class.php',

  // project_model
  'produit' => '/srv/http/resgala/lib/model/doctrine/Produit.class.php',
  'basereservation' => '/srv/http/resgala/lib/model/doctrine/base/BaseReservation.class.php',
  'baselignecommande' => '/srv/http/resgala/lib/model/doctrine/base/BaseLigneCommande.class.php',
  'baseproduit' => '/srv/http/resgala/lib/model/doctrine/base/BaseProduit.class.php',
  'produittable' => '/srv/http/resgala/lib/model/doctrine/ProduitTable.class.php',
  'reservationtable' => '/srv/http/resgala/lib/model/doctrine/ReservationTable.class.php',
  'lignecommande' => '/srv/http/resgala/lib/model/doctrine/LigneCommande.class.php',
  'reservation' => '/srv/http/resgala/lib/model/doctrine/Reservation.class.php',
  'lignecommandetable' => '/srv/http/resgala/lib/model/doctrine/LigneCommandeTable.class.php',

  // application
  'myuser' => '/srv/http/resgala/apps/frontoffice/lib/myUser.class.php',

  // modules
);
