<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/11/25 14:57:26

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'sqlite:/srv/http/resgala/data/testsdata.db',
  'name' => 'doctrine',
)),);
