# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

start_reserv:
  url: /reservation/identity
  param: { module: reswizard, action: start }

identity_save:
  url: /reservation/identity/save
  param: { module: reswizard, action: saveStart }

commande:
  url: /reservation/commande
  param: { module: reswizard, action: commande }

commande_save:
  url: /reservation/commande/save
  param: { module: reswizard, action: saveCommande }

validate:
  url: /reservation/validate
  param: { module: reswizard, action: validate }

validate_save:
  url: /reservation/validate/save
  param: { module: reswizard, action: saveValidate }

resa_done:
  url: /reservation/done
  param: { module: reswizard, action: done }

# default rules
homepage:
  url:   /
  param: { module: accueil, action: index }
