generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Reservation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          reservation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: 
        _new: {}
        paye:
          label: Marquer comme payée
      fields:
        id:
          label: "#"
        prenom:
          label: Prénom
        nom:
          label: Nom
        login:
          label: Login INSA
        paye_with:
          label: Paiement par
        banque_nom:
          label: Nom de la banque
        repas_with:
          label: Souhaite manger avec
        validated_at:
          label: Réservé le
          date_format: dd/MM à HH:MM
      list:
        title:  Liste des réservations
        #layout: stacked
        display: [id, =prenom, =nom, total_formatted, login, paye_with, banque_nom, validated_at]
        object_actions:
          _edit: ~
          paye: ~
        batch_actions:
          paye:
            label: Marqué comme payé
      show: ~
      filter:
        display: [nom, login, paye_with, banque_nom, validated_at]
      form:    ~
      edit:
        title:  Modification de la réservation de %%prenom%% %%nom%%